server:
  port: 8080
logging:
  config: classpath:log4j2.xml
spring:
  application:
    name: sync-server
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0
    timeout: 100000
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 1